---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu1204
      run_list:
        - recipe[apt]
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu1404
      run_list:
        - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[aptly::default]
      - recipe[aptly_test::default]
    attributes:
  - name: api
    run_list:
      - recipe[aptly::default]
    attributes:
      aptly:
        configure_api_service: true
